spring:
  application:
    name: namhatta-management-system
    
  datasource:
    url: jdbc:${DATABASE_URL:h2:mem:testdb}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 5000
  servlet:
    context-path: /api

logging:
  level:
    com.namhatta: INFO
    org.springframework.web: INFO

# Springdoc OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true